[package]
name = "drg_modio_audit"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
unpak = { git = "https://github.com/trumank/unpak.git", version = "0.2.0" }
